/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AEFSCTRL_H_RPCGEN
#define	_AEFSCTRL_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#define	AEFSNFSD_DEF_PORT 843
#define	AEFSCTRL_MAXPATHLEN 250
#define	AF_READONLY 1
#define	AF_MOUNTDIRTY 2
#define	AF_LAZYWRITE 4

struct addfsargs {
	char *path;
	char *key;
	int flags;
	int stor_uid;
	int stor_gid;
	int stor_mode;
	int fs_uid;
	int fs_gid;
};
typedef struct addfsargs addfsargs;

enum addfsstat {
	ADDFS_OK = 0,
	ADDFS_HAVE_KEY = 1,
	ADDFS_MAX_FS = 2,
	ADDFS_CORE = 3,
	ADDFS_FAIL = 4,
	ADDFS_DIRTY = 5,
	ADDFS_PERM = 6
};
typedef enum addfsstat addfsstat;

struct addfsres {
	addfsstat stat;
	int cr;
};
typedef struct addfsres addfsres;

#define	AEFSCTRL_PROGRAM ((unsigned long)(101438))
#define	AEFSCTRL_VERSION_1 ((unsigned long)(1))

#if defined(__STDC__) || defined(__cplusplus)
#define	AEFSCTRLPROC_NULL ((unsigned long)(0))
extern  void * aefsctrlproc_null_1(void *, CLIENT *);
extern  void * aefsctrlproc_null_1_svc(void *, struct svc_req *);
#define	AEFSCTRLPROC_ADDFS ((unsigned long)(1))
extern  addfsres * aefsctrlproc_addfs_1(addfsargs *, CLIENT *);
extern  addfsres * aefsctrlproc_addfs_1_svc(addfsargs *, struct svc_req *);
#define	AEFSCTRLPROC_FLUSH ((unsigned long)(123))
extern  void * aefsctrlproc_flush_1(void *, CLIENT *);
extern  void * aefsctrlproc_flush_1_svc(void *, struct svc_req *);
extern int aefsctrl_program_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	AEFSCTRLPROC_NULL ((unsigned long)(0))
extern  void * aefsctrlproc_null_1();
extern  void * aefsctrlproc_null_1_svc();
#define	AEFSCTRLPROC_ADDFS ((unsigned long)(1))
extern  addfsres * aefsctrlproc_addfs_1();
extern  addfsres * aefsctrlproc_addfs_1_svc();
#define	AEFSCTRLPROC_FLUSH ((unsigned long)(123))
extern  void * aefsctrlproc_flush_1();
extern  void * aefsctrlproc_flush_1_svc();
extern int aefsctrl_program_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_addfsargs(XDR *, addfsargs*);
extern  bool_t xdr_addfsstat(XDR *, addfsstat*);
extern  bool_t xdr_addfsres(XDR *, addfsres*);

#else /* K&R C */
extern bool_t xdr_addfsargs();
extern bool_t xdr_addfsstat();
extern bool_t xdr_addfsres();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AEFSCTRL_H_RPCGEN */
