/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mount.h"
#ifndef lint
/*static char sccsid[] = "from: @(#)mount.x 1.2 87/09/18 Copyr 1987 Sun Micro";*/
/*static char sccsid[] = "from: @(#)mount.x	2.1 88/08/01 4.0 RPCSRC";*/
static char rcsid[] = "mount.x,v 1.1 1994/08/04 19:01:46 wollman Exp";
#endif /* not lint */

bool_t
xdr_fhandle(register XDR *xdrs, fhandle objp)
{

	register long *buf;

	if (!xdr_opaque(xdrs, objp, FHSIZE))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_fhstatus(register XDR *xdrs, fhstatus *objp)
{

	register long *buf;

	if (!xdr_u_int(xdrs, &objp->fhs_status))
		return (FALSE);
	switch (objp->fhs_status) {
	case 0:
		if (!xdr_fhandle(xdrs, objp->fhstatus_u.fhs_fhandle))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_dirpath(register XDR *xdrs, dirpath *objp)
{

	register long *buf;

	if (!xdr_string(xdrs, objp, MNTPATHLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_name(register XDR *xdrs, name *objp)
{

	register long *buf;

	if (!xdr_string(xdrs, objp, MNTNAMLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_mountlist(register XDR *xdrs, mountlist *objp)
{

	register long *buf;

	if (!xdr_pointer(xdrs, (char **)objp, sizeof (struct mountbody), (xdrproc_t) xdr_mountbody))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_mountbody(register XDR *xdrs, mountbody *objp)
{

	register long *buf;

	if (!xdr_name(xdrs, &objp->ml_hostname))
		return (FALSE);
	if (!xdr_dirpath(xdrs, &objp->ml_directory))
		return (FALSE);
	if (!xdr_mountlist(xdrs, &objp->ml_next))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_groups(register XDR *xdrs, groups *objp)
{

	register long *buf;

	if (!xdr_pointer(xdrs, (char **)objp, sizeof (struct groupnode), (xdrproc_t) xdr_groupnode))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_groupnode(register XDR *xdrs, groupnode *objp)
{

	register long *buf;

	if (!xdr_name(xdrs, &objp->gr_name))
		return (FALSE);
	if (!xdr_groups(xdrs, &objp->gr_next))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_exports(register XDR *xdrs, exports *objp)
{

	register long *buf;

	if (!xdr_pointer(xdrs, (char **)objp, sizeof (struct exportnode), (xdrproc_t) xdr_exportnode))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_exportnode(register XDR *xdrs, exportnode *objp)
{

	register long *buf;

	if (!xdr_dirpath(xdrs, &objp->ex_dir))
		return (FALSE);
	if (!xdr_groups(xdrs, &objp->ex_groups))
		return (FALSE);
	if (!xdr_exports(xdrs, &objp->ex_next))
		return (FALSE);
	return (TRUE);
}
